server:
  port: 80

logging:
  path: ./logs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
      url: jdbc:postgresql://0.0.0.0:5432/test
      username: test
      password: test
      driver-class-name: org.postgresql.Driver
