server:
  port: 80

logging:
  path: ./logs

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST:localhost}
    non-secure-port: ${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:9990/eureka/}

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
      url: jdbc:postgresql://0.0.0.0:5432/calendar
      username: test
      password: test
      driver-class-name: org.postgresql.Driver

app:
  scheduling:
    request:
      destination:
        name: scheduling
    response:
      destination:
        name: scheduling-response



